[server]
baseUrlPath = "demos"
enableCORS = false
enableXsrfProtection = true
headless = true
port = 7860

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#3b82f6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f1f5f9"
textColor = "#0f172a"
font = "sans serif"
